product/movieproject/movieappp/urls.py
from django.urls import path, include
from . import views
app_name='movieappp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name="detail"),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

product/movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieappp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/movieproject/movieappp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    des=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    
    def __str__(self):
        return self.name

product/movieproject/movieappp/forms.py
from django import forms
from .models import movie

class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','des','year','img']

product/movieproject/movieappp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from .forms import movieform
# Create your views here.
def index(request):
    movie1=movie.objects.all()
    context={
        'movie_list':movie1
    }
    return  render(request,"index.html",context)
def detail(request,movie_id):
    Movie=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':Movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        des = request.POST.get('des', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie1=movie(name=name,des=des,year=year,img=img)
        movie1.save()

    return render(request,'add.html')

def update(request,id):
    Movie=movie.objects.get(id=id)
    form=movieform(request.POST or None, request.FILES,instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':Movie})
def delete(request,id):
    if request.method=='POST':
        Movie = movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request,'delete.html')

product/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter your movie name">
  <input type="text" name="des" placeholder="enter your movie description">
  <input type="text" name="year" placeholder="enter your movie year">
  <input type="file" name="img" >
  <input type="submit">


</form>
{% endblock %}

product/movieproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    MOVIE
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

product/movieproject/templates/delete.html
<form method="post">
  {% csrf_token %}
  Are you want to delete this movie?
  <input type="submit">
</form>

product/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
    </div>


<div class="col-md-6">
    <h2>{{movie.name}}</h2>
    <h4>{{movie.des}}</h4>
    <h3>{{movie.year}}</h3>
    
    <a class="btn btn-warning" href="{% url 'movieappp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieappp:delete' movie.id %}">delete</a>

</div>
    </div>
</div>
{% endblock %}

product/movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

product/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="250px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.des}}</p>
    <a href="{% url 'movieappp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}